apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: prd0kcr9u-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:8b1fa8e39f0ca45015027ab5b704e525af28f156@sha256:502f20c9bd9b534de0170d11c567bfb10b47cc1380f7b7b119ea847d5d4b2174
          name: container-image
